# cargo-vet audits file
#
# see https://mozilla.github.io/cargo-vet/index.html for more info how cargo-vet works

# ------------------
# first-party crates
# ------------------

[[audits.bytestring]]
version = "1.3.1"
criteria = "safe-to-deploy"
who = "Rob Ede <robjtede@icloud.com>"
notes = "Maintained by Actix team."

[[audits.local-waker]]
version = "0.1.4"
criteria = "safe-to-deploy"
who = "Rob Ede <robjtede@icloud.com>"
notes = "Maintained by Actix team."

[[audits.local-channel]]
version = "0.1.5"
criteria = "safe-to-deploy"
who = "Rob Ede <robjtede@icloud.com>"
notes = "Maintained by Actix team."

[[audits.actix-utils]]
version = "3.0.1"
criteria = "safe-to-deploy"
who = "Rob Ede <robjtede@icloud.com>"
notes = "Maintained by Actix team."

[[audits.actix-service]]
version = "2.0.2"
criteria = "safe-to-deploy"
who = "Rob Ede <robjtede@icloud.com>"
notes = "Maintained by Actix team."

[[audits.actix-codec]]
version = "0.5.2"
criteria = "safe-to-deploy"
who = "Rob Ede <robjtede@icloud.com>"
notes = "Maintained by Actix team."

[[audits.actix-rt]]
version = "2.10.0"
criteria = "safe-to-deploy"
who = "Rob Ede <robjtede@icloud.com>"
notes = "Maintained by Actix team."

[[audits.actix-macros]]
version = "0.2.4"
criteria = "safe-to-deploy"
who = "Rob Ede <robjtede@icloud.com>"
notes = "Maintained by Actix team."

# ------------------
# third-party crates
# ------------------

[[audits.actix-web-lab]]
version = "0.7.13"
criteria = "safe-to-deploy"
who = "Rob Ede <robjtede@icloud.com>"
notes = """
Maintained by member of Actix team.

While functionality is documented as experimental, it is only in terms of breaking change risks and
does not indicate that production usage of these helpers is dangerous.
"""

[[audits.actix-hash]]
version = "0.5.0"
criteria = "safe-to-deploy"
who = "Rob Ede <robjtede@icloud.com>"
notes = """
Maintained by member of Actix team.

Implementations are simple and hazardous hashing functions are marked as such in documentation.
"""
