# cargo-vet audits file
#
# see https://mozilla.github.io/cargo-vet/index.html for more info how cargo-vet works

# ------------------
# first-party crates
# ------------------

[[wildcard-audits.bytestring]]
criteria = "safe-to-deploy"
user-id = 56903 # @robjtede
start = "2021-01-01"
end = "2025-12-31"
notes = "Maintained by Actix team."

[[wildcard-audits.local-waker]]
criteria = "safe-to-deploy"
user-id = 56903 # @robjtede
start = "2021-01-01"
end = "2025-12-31"
notes = "Maintained by Actix team."

[[wildcard-audits.local-channel]]
criteria = "safe-to-deploy"
user-id = 56903 # @robjtede
start = "2021-01-01"
end = "2025-12-31"
notes = "Maintained by Actix team."

[[wildcard-audits.actix-utils]]
criteria = "safe-to-deploy"
user-id = 56903 # @robjtede
start = "2021-01-01"
end = "2025-12-31"
notes = "Maintained by Actix team."

[[wildcard-audits.actix-service]]
criteria = "safe-to-deploy"
user-id = 56903 # @robjtede
start = "2021-01-01"
end = "2025-12-31"
notes = "Maintained by Actix team."

[[wildcard-audits.actix-codec]]
criteria = "safe-to-deploy"
user-id = 56903 # @robjtede
start = "2021-01-01"
end = "2025-12-31"
notes = "Maintained by Actix team."

[[wildcard-audits.actix-rt]]
criteria = "safe-to-deploy"
user-id = 56903 # @robjtede
start = "2021-01-01"
end = "2025-12-31"
notes = "Maintained by Actix team."

[[wildcard-audits.actix-macros]]
criteria = "safe-to-deploy"
user-id = 56903 # @robjtede
start = "2021-01-01"
end = "2025-12-31"
notes = "Maintained by Actix team."

# ------------------
# third-party crates
# ------------------

[[wildcard-audits.actix-web-lab]]
criteria = "safe-to-deploy"
user-id = 56903 # @robjtede
start = "2021-01-01"
end = "2025-12-31"
notes = """
Maintained by member of Actix team.

While functionality is documented as experimental, it is only in terms of breaking change risks and
does not indicate that production usage of these helpers is dangerous.
"""

[[wildcard-audits.actix-hash]]
criteria = "safe-to-deploy"
user-id = 56903 # @robjtede
start = "2021-01-01"
end = "2025-12-31"
notes = """
Maintained by member of Actix team.

Implementations are simple and hazardous hashing functions are marked as such in documentation.
"""
